package in.ExceptionAll;


/*

ArithmeticException:-

If we Divided any Number with zero , we will get this runtime exception
ex-:5/2-----> 2
5/0---------> RE: ArithmeticException

*/

public class ArithMeticExceptionExa {
	public static void main(String[] args) {
		
		System.out.println(5/2);
		System.out.println(5/0);
	}

}
